# Generated by Django 5.1.3 on 2025-01-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=25)),
                ('data', models.DateField(blank=True)),
                ('descrizione', models.TextField()),
                ('partecipanti', models.IntegerField()),
            ],
        ),
    ]
