# Generated by Django 5.1.3 on 2024-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterModelOptions(
            name='giornalista',
            options={'verbose_name': 'Giornalista', 'verbose_name_plural': 'Giornalisti'},
        ),
        migrations.AddField(
            model_name='articolo',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='visualizzazioni',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
