# Generated by Django 5.1.3 on 2025-02-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_culturali', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='titolo',
            field=models.CharField(max_length=50),
        ),
    ]
